// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghneorgsqkvfjepscntu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdobmVvcmdzcWt2ZmplcHNjbnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzA1NTMsImV4cCI6MjA2MzYwNjU1M30.j6r0TKTvsoBkGFWXJA8aIPYcBukX_PKGOH3e7f1qgcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);